/**
 * Provenance Chain Cache
 * 
 * LRU cache for frequently accessed provenance chains
 */

import { ProvenanceChain } from './provenance-slide-service';

export interface CacheEntry {
  chain: ProvenanceChain;
  timestamp: number;
  accessCount: number;
  lastAccessed: number;
}

export interface CacheStats {
  size: number;
  maxSize: number;
  hitCount: number;
  missCount: number;
  evictionCount: number;
  hitRate: number;
}

export class ProvenanceChainCache {
  private cache: Map<string, CacheEntry>;
  private maxSize: number;
  private hitCount: number;
  private missCount: number;
  private evictionCount: number;

  constructor(maxSize: number = 50) {
    this.cache = new Map();
    this.maxSize = maxSize;
    this.hitCount = 0;
    this.missCount = 0;
    this.evictionCount = 0;
  }

  /**
   * Get cached provenance chain by key.
   * 
   * Retrieves a cached provenance chain if it exists. Updates access statistics
   * and moves the entry to the end of the cache (most recently used) for LRU
   * eviction purposes.
   * 
   * @param {string} key - Cache key (typically generated by generateKey)
   * @returns {ProvenanceChain | null} Cached chain or null if not found
   * 
   * @example
   * ```typescript
   * const key = ProvenanceChainCache.generateKey('/evolutions/advanced-automaton', '0D');
   * const chain = cache.get(key);
   * if (chain) {
   *   // Use cached chain
   * }
   * ```
   */
  get(key: string): ProvenanceChain | null {
    const entry = this.cache.get(key);
    
    if (!entry) {
      this.missCount++;
      return null;
    }

    // Update access statistics
    entry.accessCount++;
    entry.lastAccessed = Date.now();
    
    // Move to end (most recently used)
    this.cache.delete(key);
    this.cache.set(key, entry);
    
    this.hitCount++;
    return entry.chain;
  }

  /**
   * Set cached provenance chain by key.
   * 
   * Stores a provenance chain in the cache. If the cache is full, the least
   * recently used entry is evicted. If the key already exists, the entry is
   * updated and moved to the end (most recently used).
   * 
   * @param {string} key - Cache key
   * @param {ProvenanceChain} chain - Provenance chain to cache
   * 
   * @example
   * ```typescript
   * const key = ProvenanceChainCache.generateKey('/evolutions/advanced-automaton', '0D');
   * cache.set(key, chain);
   * // Chain is now cached
   * ```
   */
  set(key: string, chain: ProvenanceChain): void {
    // If key already exists, update it
    if (this.cache.has(key)) {
      const existing = this.cache.get(key)!;
      existing.chain = chain;
      existing.timestamp = Date.now();
      existing.lastAccessed = Date.now();
      existing.accessCount++;
      
      // Move to end
      this.cache.delete(key);
      this.cache.set(key, existing);
      return;
    }

    // If cache is full, evict least recently used
    if (this.cache.size >= this.maxSize) {
      this.evictLRU();
    }

    // Add new entry
    this.cache.set(key, {
      chain,
      timestamp: Date.now(),
      accessCount: 1,
      lastAccessed: Date.now()
    });
  }

  /**
   * Evict least recently used entry
   */
  private evictLRU(): void {
    if (this.cache.size === 0) return;

    // Find entry with oldest lastAccessed time
    let lruKey: string | null = null;
    let oldestTime = Infinity;

    for (const [key, entry] of this.cache.entries()) {
      if (entry.lastAccessed < oldestTime) {
        oldestTime = entry.lastAccessed;
        lruKey = key;
      }
    }

    if (lruKey) {
      this.cache.delete(lruKey);
      this.evictionCount++;
    }
  }

  /**
   * Clear all cached chains.
   * 
   * Removes all entries from the cache and resets statistics. This should be
   * called when a complete cache reset is needed.
   * 
   * @example
   * ```typescript
   * cache.clear();
   * // All cached chains are removed
   * ```
   */
  clear(): void {
    this.cache.clear();
    this.hitCount = 0;
    this.missCount = 0;
    this.evictionCount = 0;
  }

  /**
   * Invalidate cache entries matching pattern.
   * 
   * Removes cache entries whose keys match the specified pattern. Useful for
   * invalidating related entries (e.g., all chains for a specific evolution path).
   * 
   * @param {string | RegExp} pattern - Pattern to match against cache keys
   * 
   * @example
   * ```typescript
   * // Invalidate all chains for a specific evolution path
   * cache.invalidate(/^\/evolutions\/advanced-automaton/);
   * ```
   */
  invalidate(pattern: string | RegExp): void {
    const regex = typeof pattern === 'string' ? new RegExp(pattern) : pattern;
    
    for (const key of this.cache.keys()) {
      if (regex.test(key)) {
        this.cache.delete(key);
      }
    }
  }

  /**
   * Get cache statistics.
   * 
   * Returns comprehensive statistics about the cache, including size, hit/miss
   * counts, eviction count, and hit rate. Useful for monitoring cache performance.
   * 
   * @returns {CacheStats} Cache statistics object
   * 
   * @example
   * ```typescript
   * const stats = cache.getStats();
   * console.log(`Hit rate: ${(stats.hitRate * 100).toFixed(1)}%`);
   * ```
   */
  getStats(): CacheStats {
    const totalRequests = this.hitCount + this.missCount;
    const hitRate = totalRequests > 0 ? this.hitCount / totalRequests : 0;

    return {
      size: this.cache.size,
      maxSize: this.maxSize,
      hitCount: this.hitCount,
      missCount: this.missCount,
      evictionCount: this.evictionCount,
      hitRate
    };
  }

  /**
   * Generate cache key from evolution path and dimension.
   * 
   * Creates a standardized cache key from an evolution path and optional dimension.
   * This ensures consistent key generation across the application.
   * 
   * @param {string} evolutionPath - Path to the evolution directory
   * @param {string} [dimension] - Optional dimension filter (e.g., '0D', '1D')
   * @returns {string} Cache key string
   * 
   * @example
   * ```typescript
   * const key = ProvenanceChainCache.generateKey('/evolutions/advanced-automaton', '0D');
   * // key = '/evolutions/advanced-automaton:0D'
   * ```
   */
  static generateKey(evolutionPath: string, dimension?: string): string {
    return dimension ? `${evolutionPath}:${dimension}` : evolutionPath;
  }
}

// Export singleton instance
export const provenanceChainCache = new ProvenanceChainCache(50);

