version: 2
checks:
  # Security checks
  hostIPC: false
  hostPID: false
  hostNetwork: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser:
    min: 1000
  runAsGroup:
    min: 1000
  capabilities:
    drop: ["ALL"]
    add: []
  
  # Resource limits
  cpuLimits: true
  cpuRequests: true
  memoryLimits: true
  memoryRequests: true
  
  # Health checks
  livenessProbe: true
  readinessProbe: true
  
  # Image security
  imageTag: "latest"
  pullPolicy: "Always"
  
  # Networking
  hostPort: false
  serviceType: "ClusterIP"

exemptions:
  - controllerNamespaces:
      - kube-system
    rules:
      - hostNetwork
      - hostPID
      - hostIPC
  - controllerNames:
      - redis-master
      - redis-replica
    rules:
      - readOnlyRootFilesystem

actions:
  onFailure:
    - message: "Security policy violation detected"
      type: warning