#!/usr/bin/env tsx
/**
 * Generate Wikipedia-Style Documentation
 * 
 * Generates Wikipedia-style articles for all major concepts with proper citations.
 */

import * as fs from 'fs';
import * as path from 'path';
import { HierarchicalTrie } from './build-reference-trie';

interface WikipediaArticle {
  title: string;
  filename: string;
  content: string;
  citations: string[];
  externalLinks: string[];
  seeAlso: string[];
}

/**
 * Generate Wikipedia-style article
 */
function generateWikipediaArticle(
  title: string,
  content: string,
  citations: string[],
  externalLinks: string[],
  seeAlso: string[]
): string {
  const filename = title.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '');
  
  let article = `# ${title}\n\n`;
  
  // Lead section
  article += `== Overview ==\n`;
  article += `${content}\n\n`;
  
  // Table of contents (auto-generated by Wikipedia)
  article += `__TOC__\n\n`;
  
  // Main content sections
  article += `== Details ==\n`;
  article += `[Content to be expanded]\n\n`;
  
  // Citations
  if (citations.length > 0) {
    article += `== References ==\n`;
    article += `{{reflist}}\n\n`;
    citations.forEach((citation, index) => {
      article += `{{cite web | url=${citation} | title=Reference ${index + 1}}}\n`;
    });
    article += `\n`;
  }
  
  // External links
  if (externalLinks.length > 0) {
    article += `== External Links ==\n`;
    externalLinks.forEach(link => {
      const linkText = link.split('/').pop()?.replace(/_/g, ' ') || link;
      article += `* [${linkText}](${link})\n`;
    });
    article += `\n`;
  }
  
  // See also
  if (seeAlso.length > 0) {
    article += `== See Also ==\n`;
    seeAlso.forEach(item => {
      article += `* [[${item}]]\n`;
    });
    article += `\n`;
  }
  
  return article;
}

/**
 * Generate main Computational Topology Canvas article
 */
function generateMainArticle(trie: HierarchicalTrie): WikipediaArticle {
  const title = 'Computational Topology Canvas';
  const content = `The Computational Topology Canvas is a self-referential multi-agent system that implements Church encoding and integrates ProLog, DataLog, and R5RS Scheme for knowledge representation and reasoning. The system spans dimensions 0D through 7D, with each dimension representing a different level of computational abstraction.

The framework uses JSONL files as both data and executable code, enabling true metacircular evaluation. It implements a blackboard architecture where agents coordinate through a shared knowledge base, queryable via SPARQL, ProLog, and DataLog.

Key features include dimensional progression from foundational lambda calculus (0D) through quantum computing (7D), self-modification capabilities, and integration with CI/CD pipelines for automated deployment and testing.`;
  
  const citations = [
    'https://en.wikipedia.org/wiki/Church_encoding',
    'https://en.wikipedia.org/wiki/Multi-agent_system',
    'https://en.wikipedia.org/wiki/Lambda_calculus',
    'https://en.wikipedia.org/wiki/Prolog',
    'https://en.wikipedia.org/wiki/Datalog'
  ];
  
  const externalLinks = [
    'https://en.wikipedia.org/wiki/Computational_topology',
    'https://en.wikipedia.org/wiki/Blackboard_system',
    'https://en.wikipedia.org/wiki/Metacircular_evaluator'
  ];
  
  const seeAlso = [
    'Church Encoding',
    'Multi Agent System',
    'Meta Log Framework',
    'Dimensional Progression',
    'Blackboard Architecture'
  ];
  
  return {
    title,
    filename: 'Computational_Topology_Canvas.md',
    content: generateWikipediaArticle(title, content, citations, externalLinks, seeAlso),
    citations,
    externalLinks,
    seeAlso
  };
}

/**
 * Generate concept articles
 */
function generateConceptArticles(trie: HierarchicalTrie): WikipediaArticle[] {
  const articles: WikipediaArticle[] = [];
  
  const concepts = [
    {
      title: 'Church Encoding',
      content: `Church encoding is a method of representing data and operators in lambda calculus. The Computational Topology Canvas implements Church numerals, Church booleans, and Church pairs as the foundational layer (0D-2D) of its architecture.

The system uses Church encoding to represent:
- Natural numbers: zero, one, successor, addition, multiplication, exponentiation
- Booleans: true, false, conditional, logical operations
- Pairs: for representing structured data

This encoding provides the mathematical foundation for all higher-dimensional operations.`,
      citations: ['https://en.wikipedia.org/wiki/Church_encoding'],
      externalLinks: ['https://en.wikipedia.org/wiki/Church_encoding'],
      seeAlso: ['Lambda Calculus', 'Y Combinator', 'Dimensional Progression']
    },
    {
      title: 'Multi Agent System',
      content: `The Computational Topology Canvas implements a multi-agent system with 15 specialized agents operating across dimensions 0D-7D. Each agent is responsible for specific operations within its dimensional scope.

Foundation agents (0D-2D) handle Church encoding and basic topology. Operational agents (3D-4D) manage algebraic operations and network coordination. Advanced agents (5D-7D) implement consensus, intelligence, and quantum operations.

Agents communicate through a blackboard architecture using JSONL files as the shared knowledge base. They coordinate via SPARQL queries, ProLog inference, and DataLog fact extraction.`,
      citations: ['https://en.wikipedia.org/wiki/Multi-agent_system'],
      externalLinks: ['https://en.wikipedia.org/wiki/Multi-agent_system'],
      seeAlso: ['Blackboard Architecture', 'Dimensional Progression', 'Meta Log Framework']
    },
    {
      title: 'Meta Log Framework',
      content: `The Meta-Log Framework integrates ProLog, DataLog, and R5RS Scheme to provide a unified logic programming interface for the Computational Topology Canvas.

ProLog enables unification and resolution-based inference. DataLog provides declarative fact extraction and querying. R5RS Scheme functions implement Church encoding operations and canvas manipulation.

The framework supports:
- SPARQL queries over RDF triples
- ProLog goal resolution
- DataLog fixed-point computation
- SHACL validation for constraint checking`,
      citations: [
        'https://en.wikipedia.org/wiki/Prolog',
        'https://en.wikipedia.org/wiki/Datalog',
        'https://en.wikipedia.org/wiki/Revised_Report_on_the_Algorithmic_Language_Scheme'
      ],
      externalLinks: [
        'https://en.wikipedia.org/wiki/Prolog',
        'https://en.wikipedia.org/wiki/Datalog'
      ],
      seeAlso: ['ProLog Integration', 'DataLog Integration', 'R5RS Integration']
    },
    {
      title: 'Dimensional Progression',
      content: `The Computational Topology Canvas organizes computation across eight dimensions (0D-7D), each representing a different level of abstraction:

- 0D: Quantum vacuum topology and identity processes
- 1D: Temporal evolution and Church successor operations
- 2D: Spatial structure and pattern encoding
- 3D: Algebraic operations (addition, multiplication, exponentiation)
- 4D: Network operations and spacetime structure
- 5D: Distributed consensus and blockchain operations
- 6D: Emergent AI and neural network operations
- 7D: Quantum superposition and entanglement

This dimensional progression enables systematic construction of complex systems from foundational primitives.`,
      citations: ['https://en.wikipedia.org/wiki/Dimension'],
      externalLinks: ['https://en.wikipedia.org/wiki/Dimension'],
      seeAlso: ['Church Encoding', 'Multi Agent System']
    },
    {
      title: 'Blackboard Architecture',
      content: `The Computational Topology Canvas uses a blackboard architecture where agents share information through a common data structure (JSONL files). This enables:

- Decoupled agent communication
- Shared knowledge representation
- Query-based coordination
- Self-modification through blackboard updates

The blackboard serves as both data storage and executable code, enabling metacircular evaluation. Agents query the blackboard using SPARQL, ProLog, and DataLog to coordinate operations.`,
      citations: ['https://en.wikipedia.org/wiki/Blackboard_system'],
      externalLinks: ['https://en.wikipedia.org/wiki/Blackboard_system'],
      seeAlso: ['Multi Agent System', 'Meta Log Framework']
    },
    {
      title: 'CanvasL Format',
      content: `CanvasL is an extended JSONL format that adds directives, R5RS function calls, dimension references, and Scheme expressions to standard JSONL.

Key features:
- Directives: @version, @schema for metadata
- R5RS function calls: {"type": "r5rs-call", "function": "r5rs:church-add"}
- Dimension references: {"dimension": "0D"}
- Node references: {"fromNode": "#0D-topology"}
- Scheme expressions: {"expression": "(church-add 2 3)"}

CanvasL enables self-referential canvas files that can execute operations and reference other dimensions.`,
      citations: ['https://en.wikipedia.org/wiki/JSON'],
      externalLinks: ['https://en.wikipedia.org/wiki/JSON'],
      seeAlso: ['R5RS Integration', 'Meta Log Framework']
    },
    {
      title: 'Automaton System',
      content: `The automaton system implements self-referential execution of JSONL/CanvasL files. Automatons can:

- Load and save JSONL canvas files
- Execute actions based on dimensional progression
- Generate Church encoding patterns
- Validate self-reference structures
- Coordinate with multi-agent system

The system supports multiple execution modes:
- Built-in intelligence (continuous-automaton.ts)
- AI-powered via Ollama (ollama-automaton.ts)
- Core engine operations (advanced-automaton.ts)
- Bootstrap process (bootstrap-automaton.ts)`,
      citations: ['https://en.wikipedia.org/wiki/Automata_theory'],
      externalLinks: ['https://en.wikipedia.org/wiki/Automata_theory'],
      seeAlso: ['Self Reference', 'Dimensional Progression']
    }
  ];
  
  for (const concept of concepts) {
    articles.push({
      title: concept.title,
      filename: `${concept.title.replace(/\s+/g, '_')}.md`,
      content: generateWikipediaArticle(
        concept.title,
        concept.content,
        concept.citations,
        concept.externalLinks,
        concept.seeAlso
      ),
      citations: concept.citations,
      externalLinks: concept.externalLinks,
      seeAlso: concept.seeAlso
    });
  }
  
  return articles;
}

/**
 * Generate agent articles
 */
function generateAgentArticles(trie: HierarchicalTrie): WikipediaArticle[] {
  const articles: WikipediaArticle[] = [];
  
  const agents = [
    { name: '0D Topology Agent', dimension: '0D', purpose: 'Maintain quantum vacuum topology and identity processes' },
    { name: '1D Temporal Agent', dimension: '1D', purpose: 'Handle temporal evolution and Church successor operations' },
    { name: '2D Structural Agent', dimension: '2D', purpose: 'Manage spatial structure and pattern encoding' },
    { name: '3D Algebraic Agent', dimension: '3D', purpose: 'Perform Church algebra operations' },
    { name: '4D Network Agent', dimension: '4D', purpose: 'Manage spacetime and network operations' },
    { name: '5D Consensus Agent', dimension: '5D', purpose: 'Implement distributed consensus and blockchain operations' },
    { name: '6D Intelligence Agent', dimension: '6D', purpose: 'Handle emergent AI and neural network operations' },
    { name: '7D Quantum Agent', dimension: '7D', purpose: 'Manage quantum superposition and entanglement' }
  ];
  
  for (const agent of agents) {
    const content = `The ${agent.name} operates at dimension ${agent.dimension} of the Computational Topology Canvas. ${agent.purpose}.

This agent coordinates with other dimensional agents through the blackboard architecture, using SPARQL queries, ProLog inference, and DataLog fact extraction to share information and coordinate operations.`;
    
    articles.push({
      title: agent.name,
      filename: `${agent.name.replace(/\s+/g, '_')}.md`,
      content: generateWikipediaArticle(
        agent.name,
        content,
        ['https://en.wikipedia.org/wiki/Multi-agent_system'],
        ['https://en.wikipedia.org/wiki/Multi-agent_system'],
        ['Multi Agent System', 'Dimensional Progression']
      ),
      citations: ['https://en.wikipedia.org/wiki/Multi-agent_system'],
      externalLinks: ['https://en.wikipedia.org/wiki/Multi-agent_system'],
      seeAlso: ['Multi Agent System', 'Dimensional Progression']
    });
  }
  
  return articles;
}

/**
 * Generate technical articles
 */
function generateTechnicalArticles(trie: HierarchicalTrie): WikipediaArticle[] {
  const articles: WikipediaArticle[] = [];
  
  const technical = [
    {
      title: 'R5RS Integration',
      content: `The Computational Topology Canvas integrates R5RS Scheme functions for Church encoding operations and canvas manipulation. R5RS functions are invoked via CanvasL format using {"type": "r5rs-call"} syntax.

Key R5RS functions include:
- Church encoding: church-zero, church-succ, church-add, church-mult, church-exp
- JSONL operations: parse-jsonl-canvas, extract-facts, query-facts
- RDF operations: jsonl-to-rdf, rdf-query, sparql-query
- Logic programming: prolog-query, datalog-query
- Validation: load-shacl-shapes, shacl-validate`,
      citations: ['https://en.wikipedia.org/wiki/Revised_Report_on_the_Algorithmic_Language_Scheme'],
      seeAlso: ['Meta Log Framework', 'CanvasL Format']
    },
    {
      title: 'ProLog Integration',
      content: `ProLog integration enables unification and resolution-based inference in the Computational Topology Canvas. The system uses ProLog for:

- Goal resolution and backward chaining
- Inheritance reasoning via vertical relationships
- Constraint satisfaction
- Multi-agent coordination

ProLog queries are executed via r5rs:prolog-query function, which builds a ProLog database from JSONL facts and resolves goals.`,
      citations: ['https://en.wikipedia.org/wiki/Prolog'],
      seeAlso: ['Meta Log Framework', 'R5RS Integration']
    },
    {
      title: 'DataLog Integration',
      content: `DataLog provides declarative fact extraction and querying capabilities. The system uses DataLog for:

- Extracting facts from JSONL canvas files
- Fixed-point computation for recursive queries
- Pattern matching and unification
- Relationship traversal

DataLog queries are executed via r5rs:datalog-query function, which builds a DataLog program from extracted facts.`,
      citations: ['https://en.wikipedia.org/wiki/Datalog'],
      seeAlso: ['Meta Log Framework', 'R5RS Integration']
    },
    {
      title: 'SHACL Validation',
      content: `SHACL (Shapes Constraint Language) validation ensures compliance with RFC2119 specifications and architectural constraints. The system validates:

- Label constraints: rdfs:label must be string
- Identity constraints: owl:sameAs minimum count 1
- Technology constraints: prov:used must match specifications
- Dimensional constraints: agents must implement exactly one system per dimension

SHACL validation is performed via r5rs:shacl-validate function.`,
      citations: ['https://en.wikipedia.org/wiki/SHACL'],
      seeAlso: ['Meta Log Framework', 'R5RS Integration']
    },
    {
      title: 'RDF SPARQL Integration',
      content: `RDF and SPARQL integration enables semantic querying over the Computational Topology Canvas. JSONL files are converted to RDF triples, enabling:

- SPARQL queries over canvas data
- Semantic relationship traversal
- Knowledge graph construction
- Linked data integration

RDF conversion is performed via r5rs:jsonl-to-rdf, and queries via r5rs:sparql-query.`,
      citations: [
        'https://en.wikipedia.org/wiki/Resource_Description_Framework',
        'https://en.wikipedia.org/wiki/SPARQL'
      ],
      seeAlso: ['Meta Log Framework', 'R5RS Integration']
    }
  ];
  
  for (const tech of technical) {
    articles.push({
      title: tech.title,
      filename: `${tech.title.replace(/\s+/g, '_')}.md`,
      content: generateWikipediaArticle(
        tech.title,
        tech.content,
        tech.citations,
        tech.citations,
        tech.seeAlso
      ),
      citations: tech.citations,
      externalLinks: tech.citations,
      seeAlso: tech.seeAlso
    });
  }
  
  return articles;
}

/**
 * Generate all Wikipedia articles
 */
async function generateAllWikipediaArticles(): Promise<void> {
  console.log('📝 Generating Wikipedia-style articles...');
  
  // Load frontmatter trie
  const triePath = path.join(__dirname, 'frontmatter-trie.json');
  if (!fs.existsSync(triePath)) {
    throw new Error(`Frontmatter trie not found: ${triePath}. Run extract-frontmatter-trie.ts first.`);
  }
  
  const trie: any = JSON.parse(fs.readFileSync(triePath, 'utf-8'));
  
  // Load citations
  const citationsPath = path.join(__dirname, 'academic-citations.json');
  const citations = JSON.parse(fs.readFileSync(citationsPath, 'utf-8'));
  
  // Generate articles
  const mainArticle = generateMainArticle(trie, citations);
  const conceptArticles = generateConceptArticles(trie, citations);
  const agentArticles = generateAgentArticles(trie, citations);
  
  const allArticles = [mainArticle, ...conceptArticles, ...agentArticles];
  
  // Write articles
  for (const article of allArticles) {
    const filePath = path.join(__dirname, article.filename);
    fs.writeFileSync(filePath, article.content);
    console.log(`   ✓ Generated: ${article.filename}`);
  }
  
  console.log(`\n✅ Generated ${allArticles.length} Wikipedia-style articles`);
}

/**
 * Main execution
 */
async function main() {
  try {
    await generateAllWikipediaArticles();
  } catch (error) {
    console.error('❌ Error generating Wikipedia articles:', error);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

export { generateAllWikipediaArticles };
